os: linux
dist: focal

version: ~> 1.0

env:
  global:
    - IMAGE_NAME=pvphan/ci
    - IMAGE_TAG=latest

jobs:
  include:
    - stage: "Build and test"
      name: "Build docker image and run tests"
      script:
        - make test

branches:
  only:
    - main
